---
- name: Setup Web Server
  hosts: all
  remote_user: root
  become: yes
  vars_files:
    - vars/default.yaml

  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
          upgrade: yes
          update_cache: yes

    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
#      loop: [ 'aptitude' ]

    - name: Install Apache Server
      apt:
        name: apache2

    - name: Create document root
      file:
        path: "/var/www/html"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'

    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Read-write git checkout from github
      ansible.builtin.git:
        repo: https://github.com/f1amy/laravel-realworld-example-app.git
        dest: /var/www/html
        single_branch: yes
        version: main
        force: yes


    - name: Set up Apache virtual Host
      template:
        src: "files/apache.conf"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"

    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: Reload Apache


    - name: Enable new site
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache

    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

    - name: Install PHP
      apt:
        pkg:
          - php 
          - php8.1 
          - php8.1-curl 
          - libapache2-mod-php
          - php8.1-dev 
          - php8.1-bcmath 
          - php8.1-zip 
          - php8.1-mbstring
          - php-json
          - php8.1-mysql
          - php8.1-gd
          - php8.1-xml 
          - php8.1-tokenizer
          - php-common
      tags:
          - composer-tag 
    - name: Download and install Composer
      shell: curl -sS https://getcomposer.org/installer | php
      args:
        chdir: /usr/src/
        creates: /usr/local/bin/composer
        warn: false
      become: yes

    - name: Add Composer to global path
      copy: 
        dest: /usr/local/bin/composer
        group: root
        mode: '0755'
        owner: root
        src: /usr/src/composer.phar
        remote_src: yes
      become: yes 
      
    # - name: Install Composer dependencies
    #   composer:
    #     command: create-project
    #     arguments: laravel/laravel /var/www/lmth ~1.0
    #     working_dir: /var/www/html
    #     prefer_dist: yes
    #   become_user: ubuntu
    #   tags:
    #      - composer-tag

    # - name: Install Composer Update  
    #   composer:
    #     command: update
    #     working_dir: /var/www/html  
    #   become_user: ubuntu              
    #   tags:
    #       - composer-tag        

    # - name: Install Composer dependencies  
    #   composer:
    #     command: install
    #     working_dir: /var/www/html 
    #   become_user: ubuntu
    #   tags:
    #       - composer-tag

    - name: Installing Mysql  and dependencies
      apt: 
       pkg:
          - mysql-server
          - mysql-client 
          - python3-mysqldb
          - libmysqlclient-dev      
      tags:
        - mysql-tag     
      become: yes
      # package:
      #  name: apt
      #  state: present
      #  update_cache: yes
        
    - name: Start and enable mysql service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Creating mysql user
      mysql_user:
        name: "{{db_user}}"
        password: "{{db_pass}}"
        priv: '*.*:ALL'
        host: '%'
        state: present
    - name: creating Database
      mysql_db:
        name: "{{db_name}}"
        state: present

    - name: Change domain pointing.
      lineinfile:
        path: /etc/hosts
        line: 18.212.233.245 wandexdev.me
        line: 54.146.234.37 

  #  - name: Run migrations and seeders
  #    command: php {{ app_root }}/artisan migrate --seed
      
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /var/www/html/storage/logs/laravel.log
        owner: www-data
        group: www-data
        mode: '0755'

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted

    - name: Restart mysql
      service:
        name: mysql
        state: restarted    

