- name: deploy
  become: true
  hosts: SLAVE
  vars_files:
    - vars/main.yml
  roles:
    - setup
    - apache2
    - php
    - composer
    - mysql
      #    - geerlingguy.mysql
    - pgsql
    - deploy
    
