---
# tasks file for pgsql

- name: Send bash script on slave
  template:
    src: pgsql.sh.j2
    dest: "/home/ubuntu/pgsql.sh"
    mode: "0777"

- name: Execute the script
  command: sh /home/ubuntu/pgsql.sh
