---
app_user: "root"
web_user: "apache"
http_host: "wandexdev.me"
http_conf: "laravelapp.conf"
http_port: "80"
disable_default: true
db_name: test_db
db_user: admin
db_pass: passwordxxx
app_root: /var/www/laravel-realworld-example-app
#item: myqsl
